spring:
  application:
    name: bookingapp
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always

jwt:
  expiration: 86400000